# Change these first
owner: ialopezc # Tu nombre de usuario de GitHub
repo: upptime # Nombre del repositorio de GitHub
user-agent: ialopezc

sites: # Lista de puntos finales para rastrear

  - name: Efectivale .com.mx
    url: http://www.efectivale.com.mx/
    icon: http://www.efectivale.com.mx/static/website/img/home/favicon.ico
    __dangerous__disable_verify_host: true
  - name: Efectivale .com.mx certificado ssl
    url: https://www.efectivale.com.mx/
    icon: https://cdn-icons-png.flaticon.com/512/1320/1320569.png

  - name: Efectivale .com.mx TEST
    url: http://$SITE_EFV_TEST
    icon: http://www.efectivale.com.mx/static/website/img/home/favicon.ico
    __dangerous__disable_verify_host: true
  - name: Efectivale .com.mx TEST certificado ssl
    url: https://$SITE_EFV_TEST
    icon: https://cdn-icons-png.flaticon.com/512/1320/1320569.png
    
  - name: Efectivale .com
    url: http://www.efectivale.com/combustible1/
    icon: http://www.efectivale.com.mx/static/website/img/home/favicon.ico
    __dangerous__disable_verify_host: true
  - name: Efectivale .com certificado ssl
    url: https://www.efectivale.com/combustible1/
    icon: https://cdn-icons-png.flaticon.com/512/1320/1320569.png

  - name: Vales de Gasolina
    url: http://www.valesdegasolina.com/
    icon: http://www.efectivale.com.mx/static/website/img/home/favicon.ico
    __dangerous__disable_verify_host: true
  - name: Vales de Gasolina certificado ssl
    url: https://www.valesdegasolina.com/
    icon: https://cdn-icons-png.flaticon.com/512/1320/1320569.png

  - name: Vales de Gasolina TEST
    url: http://$SITE_VDD_TEST
    icon: http://www.efectivale.com.mx/static/website/img/home/favicon.ico
    __dangerous__disable_verify_host: true
  - name: Vales de Gasolina TEST certificado ssl
    url: https://$SITE_VDD_TEST
    icon: https://cdn-icons-png.flaticon.com/512/1320/1320569.png
    
  - name: Vales de Despensa
    url: http://www.valesdedespensa.com/
    icon: http://www.efectivale.com.mx/static/website/img/home/favicon.ico
    __dangerous__disable_verify_host: true
  - name: Vales de Despensa certificado ssl
    url: https://www.valesdedespensa.com/
    icon: https://cdn-icons-png.flaticon.com/512/1320/1320569.png
    
  - name: Vales de Despensa TEST
    url: http://$SITE_VDG_TEST
    icon: http://www.efectivale.com.mx/static/website/img/home/favicon.ico
    __dangerous__disable_verify_host: true
  - name: Vales de Despensa TEST certificado ssl
    url: https://$SITE_VDG_TEST
    icon: https://cdn-icons-png.flaticon.com/512/1320/1320569.png
    
  - name: Efectimapas
    url: http://efectimapas.com/
    icon: http://www.efectivale.com.mx/static/website/img/home/favicon.ico
    __dangerous__disable_verify_host: true
  - name: Efectimapas certificado ssl
    url: https://efectimapas.com/
    icon: https://cdn-icons-png.flaticon.com/512/1320/1320569.png
    
  - name: Automatic Saving Tools
    url: http://$SITE_AST
    icon: http://www.efectivale.com.mx/static/website/img/home/favicon.ico
    __dangerous__disable_verify_host: true
  - name: Automatic Saving Tools certificado ssl
    url: https://$SITE_AST
    icon: https://cdn-icons-png.flaticon.com/512/1320/1320569.png
    
  - name: Sistema de leads
    url: http://$SITE_SDL
    icon: http://www.efectivale.com.mx/static/website/img/home/favicon.ico
    __dangerous__disable_verify_host: true
  - name: Sistema de leads certificado ssl
    url: https://$SITE_SDL
    icon: https://cdn-icons-png.flaticon.com/512/1320/1320569.png
  
  - name: CMS Facebook
    url: http://www.efectivale.com/cms/
    icon: http://www.efectivale.com.mx/static/website/img/home/favicon.ico
    __dangerous__disable_verify_host: true
  - name: CMS Facebook certificado ssl
    url: https://www.efectivale.com/cms/
    icon: https://cdn-icons-png.flaticon.com/512/1320/1320569.png
    
  - name: EfectiNet
    url: http://www.efectivale.com.mx/efectinet/login
    icon: http://www.efectivale.com.mx/static/website/img/home/favicon.ico
    __dangerous__disable_verify_host: true
  - name: EfectiNet certificado ssl
    url: https://www.efectivale.com.mx/efectinet/login
    icon: https://cdn-icons-png.flaticon.com/512/1320/1320569.png
    
  - name: Efectifintech
    url: http://www.efectifintech.com.mx/
    icon: http://www.efectivale.com.mx/static/website/img/home/favicon.ico
    __dangerous__disable_verify_host: true
  - name: Efectifintech certificado ssl
    url: https://www.efectifintech.com.mx/
    icon: https://cdn-icons-png.flaticon.com/512/1320/1320569.png
    
  - name: Va Contigo
    url: http://www.efectivalebeneficios.com/
    icon: http://www.efectivale.com.mx/static/website/img/home/favicon.ico
    __dangerous__disable_verify_host: true
  - name: Va Contigo certificado ssl
    url: https://www.efectivalebeneficios.com/
    icon: https://cdn-icons-png.flaticon.com/512/1320/1320569.png
    
assignees: # Usuarios para asignar problemas de tiempo de inactividad
  - ialopezc

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Isaac Lopez Upptime
  introTitle: "**Upptime** es el monitor de tiempo de actividad de c칩digo abierto y la p치gina de estado, impulsado completamente por GitHub."
  introMessage: Esta es una p치gina de estado de muestra que usa datos en **tiempo real** de nuestro [GitHub repository](https://github.com/upptime/upptime). No se requiere servidor, solo acciones, problemas y p치ginas de GitHub. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
