# Change these first
owner: ialopezc # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Vales de Gasolina
    url: http://www.valesdegasolina.com/
    icon: http://www.efectivale.com.mx/static/website/img/home/favicon.ico
    __dangerous__disable_verify_host: true
  - name: Vales de Gasolina certificado ssl
    url: https://www.valesdegasolina.com/
    icon: https://www.efectivale.com.mx/static/website/img/home/favicon.ico
    
  - name: Vales de Despensa
    url: http://www.valesdedespensa.com/
    icon: http://www.efectivale.com.mx/static/website/img/home/favicon.ico
    __dangerous__disable_verify_host: true
  - name: Vales de Despensa certificado ssl
    url: https://www.valesdedespensa.com/
    icon: https://www.efectivale.com.mx/static/website/img/home/favicon.ico
    
  - name: Efectimapas
    url: http://www.efectimapas.com/
    icon: http://www.efectivale.com.mx/static/website/img/home/favicon.ico
    __dangerous__disable_verify_host: true
  - name: Efectimapas certificado ssl
    url: https://www.efectimapas.com/
    icon: https://www.efectivale.com.mx/static/website/img/home/favicon.ico
    
assignees:
  - ialopezc

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: demo.upptime.js.org
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Isaac Lopez Status
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
